[capability::read_slack_alerts_credential]

[role_slack_alert_action]
read_slack_alerts_credential = enabled

[role_sc_admin]
read_slack_alerts_credential = enabled

[role_admin]
read_slack_alerts_credential = enabled
