name: Tests

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            - name: Install black
              run: pip install black==24.4.2
            - name: Check formatting
              run: black --check additional_packaging.py package/bin tests

    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            - name: Install test dependencies
              run: pip install pytest
            - name: Run unit tests
              run: pytest
